export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const ADD_ITEM_IN_CART = "ADD_ITEM_IN_CART";
export const SHOW_CART_DLG = "SHOW_CART_DLG";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const TOGGLE_MENU = "TOGGLE_MENU";
export const UPDATE_CART_ITEM_QUANTITY = "UPDATE_CART_ITEM_QUANTITY";
export const SET_CHECKEDOUT_ITEMS = "SET_CHECKEDOUT_ITEMS";
